-- Insert 30 additional sample items to the existing items table
INSERT INTO public.items (name, description, status) VALUES
  ('Advanced Analytics Tool', 'Comprehensive analytics dashboard for business intelligence', 'active'),
  ('Customer Support Portal', 'Self-service portal for customer inquiries and support tickets', 'active'),
  ('Inventory Management System', 'Real-time inventory tracking and management solution', 'active'),
  ('Email Marketing Campaign', 'Automated email marketing system with personalization', 'pending'),
  ('Social Media Scheduler', 'Schedule and manage social media posts across platforms', 'active'),
  ('Project Management Hub', 'Centralized project tracking and team collaboration tool', 'active'),
  ('Financial Reporting Module', 'Generate detailed financial reports and analytics', 'inactive'),
  ('User Authentication Service', 'Secure user login and authentication system', 'active'),
  ('Content Management System', 'Easy-to-use CMS for website content management', 'active'),
  ('API Gateway Service', 'Centralized API management and routing solution', 'active'),
  ('Data Backup Solution', 'Automated data backup and recovery system', 'pending'),
  ('Mobile App Framework', 'Cross-platform mobile application development framework', 'active'),
  ('E-commerce Platform', 'Complete online store solution with payment integration', 'active'),
  ('Video Streaming Service', 'High-quality video streaming and content delivery', 'inactive'),
  ('Chat Application', 'Real-time messaging and communication platform', 'active'),
  ('Document Scanner', 'OCR-powered document scanning and digitization tool', 'active'),
  ('Weather Monitoring System', 'Real-time weather data collection and analysis', 'active'),
  ('Task Automation Engine', 'Workflow automation and task scheduling system', 'pending'),
  ('Security Monitoring Tool', 'Network security monitoring and threat detection', 'active'),
  ('Learning Management System', 'Online education and training platform', 'active'),
  ('Calendar Integration Service', 'Unified calendar management across platforms', 'active'),
  ('File Storage Solution', 'Secure cloud file storage and sharing service', 'inactive'),
  ('Performance Analytics', 'Application performance monitoring and optimization', 'active'),
  ('Survey Creation Tool', 'Create and distribute surveys with analytics', 'active'),
  ('Notification Service', 'Multi-channel notification delivery system', 'active'),
  ('Image Processing API', 'Advanced image manipulation and processing service', 'pending'),
  ('Database Migration Tool', 'Automated database schema migration utility', 'active'),
  ('Code Review Platform', 'Collaborative code review and quality assurance tool', 'active'),
  ('Event Management System', 'Complete event planning and management solution', 'inactive'),
  ('Resource Planning Tool', 'Enterprise resource planning and allocation system', 'active');
